add templates for CoC, Contributing and Issues
alexmorley/meta-open-database pull request #9
Opened 2019-01-06 16:05 UTC by dannycolin

Related to #8

2019-01-14 09:54 UTC, alexmorley requested changes
I think if we leave out the contributing.md (that'll take a little bit of work), then we can merge this so that the others are in place.

2019-01-14 09:59 UTC, alexmorley commented on CODE_OF_CONDUCT.md
> +reported by contacting any of the project team at (Alex: alex0morley@gmail.com, Danny: XX@X.com, ?). All
@johav Would you be OK to be on this list?

2019-01-14 12:47 UTC, dannycolin commented
> I think if we leave out the contributing.md (that'll take a little bit of work), then we can merge this so that the others are in place.

Or we could add a note at the top. So if anyone has the time to do it before me then s/he'll have a template instead of starting from scratch. What do you thing?

2019-01-14 15:49 UTC, alexmorley commented
> > I think if we leave out the contributing.md (that'll take a little bit of work), then we can merge this so that the others are in place.

> Or we could add a note at the top. So if anyone has the time to do it before me then s/he'll have a template instead of starting from scratch. What do you thing?

Sounds like a good idea.

2019-01-14 16:35 UTC, dannycolin commented
> Sounds like a good idea.

Done. :wink:

2019-01-18 16:09 UTC, alexmorley approved these changes

2019-01-18 16:09 UTC, merged